services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: clave
      POSTGRES_DB: midb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./Back
    container_name: wildfly-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: midb
      DB_USER: usuario
      DB_PASSWORD: clave

  frontend:
    build: ./Front
    container_name: angular-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  postgres_data: